### ISSUE TITLE
NoneType object has no attribute 'text'

### ISSUE THREAD

**Issue by himanshu64** [Deepakchawla/Mobile-Phone-Dataset-GSMArena#15]
Traceback (most recent call last):
  File "scrape.py", line 155, in <module>
    obj.save_specification_to_file()
  File "scrape.py", line 131, in save_specification_to_file
    datum = self.crawl_phones_models_specification(value, brand[0])
  File "scrape.py", line 77, in crawl_phones_models_specification
    model_name = soup.find(class_='specs-phone-name-title').text
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by oldmonkABA** [comment]
I am getting the same error

**Comment by patelanand553** [comment]
found any solution.?
