### ISSUE TITLE
List index out of range error

### ISSUE THREAD

**Issue by kalyantm** [Deepakchawla/Mobile-Phone-Dataset-GSMArena#6]
Hey, I was trying to use the library and encountered the following error when I did a `python gsmarena_scraping.py`

```Traceback (most recent call last):
  File "gsmarena_scraping.py", line 154, in <module>
    obj.save_specification_to_file()
  File "gsmarena_scraping.py", line 120, in save_specification_to_file
    phone_brand = self.crawl_phone_brands()
  File "gsmarena_scraping.py", line 44, in crawl_phone_brands
    table = soup.find_all('table')[0]
IndexError: list index out of range

I'm new to web scraping (and python in general), any pointers would be super helpful, thanks!

**Comment by muhammadfyuliandi** [comment]
Are you already solved the issues? could you guide me?

**Comment by ksskskksks** [comment]
'pwd' is not recognized as an internal or external command,
operable program or batch file.
GSMArenaDataset directory already exists
Traceback (most recent call last):
  File "gsmarena_scraping.py", line 134, in <module>
    obj.save_specification_to_file()
  File "gsmarena_scraping.py", line 107, in save_specification_to_file
    files_list = self.check_file_exists()
  File "gsmarena_scraping.py", line 102, in check_file_exists
    return os.listdir(self.absolute_path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: '/GSMArenaDataset'

i tried the history version of the gsmarena_scraping.py still cannot run the code ,can you helme to solve the problem? i am new in the python. thanks.

**Comment by sharjeelm** [comment]
@ksskskksks I think this code was made to run on linux as I got same error in case of running on windows and for case of linux there was no such error.

**Comment by 0810nitesh** [comment]
Just use 'cd' instead of pwd for windows

**Comment by 0810nitesh** [comment]
> 'pwd' is not recognized as an internal or external command,
> operable program or batch file.
> GSMArenaDataset directory already exists
> Traceback (most recent call last):
> File "gsmarena_scraping.py", line 134, in
> obj.save_specification_to_file()
> File "gsmarena_scraping.py", line 107, in save_specification_to_file
> files_list = self.check_file_exists()
> File "gsmarena_scraping.py", line 102, in check_file_exists
> return os.listdir(self.absolute_path)
> FileNotFoundError: [WinError 3] The system cannot find the path specified: '/GSMArenaDataset'
> 
> i tried the history version of the gsmarena_scraping.py still cannot run the code ,can you helme to solve the problem? i am new in the python. thanks.

Use 'cd' instead of pwd for windows
